version: '3.3'

services:
  go:
    build: # Use the Dockerfile from the current directory to build container.
      context: .
    container_name: go
    ports: 
      - "8090:8090"
    depends_on: 
      - "db"
  
  db:
    image: mysql:latest # use latest version of mysql
    container_name: db # add a name for the container
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment: 
      
      - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
      - "MYSQL_USER=${DB_USER}"
      - "MYSQL_PASSWORD=${DB_PASSWORD}"
      - "MYSQL_DATABASE=${DB_NAME}" 
    volumes:
      - my-db:/var/lib/mysql
    ports:
      - '3305:3306'
 
volumes: # add volume to persist data.
  my-db: